daodejing/urls.py
from django.conf.urls import patterns,url

from daodejing import views

urlpatterns=patterns('',
                     url(r'^$',views.index,name='index'),
                     url(r'^(?P<daodej_id>\d+)/$',views.detail,name='detail'),
                     url(r'^getone/$',views.getone,name='getone'),
                     url(r'^(?P<poll_id>\d+)/results/$',views.results,name='results'),
                     url(r'^(?P<poll_id>\d+)/vote/$',views.vote,name='vote'),
                     )

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     url(r'^$', 'daodejing.views.index', name='index'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^daodejing/',include('daodejing.urls',namespace="daodejing")),
)

daodejing/models.py
from django.db import models
import datetime
from django.utils import timezone

class Daodej(models.Model):
    banben=models.IntegerField(default=0)
    zhangjie=models.IntegerField()
    zhangming=models.CharField(max_length=50)
    jingwen=models.CharField(max_length=500)
    def __str__(self):
        return self.zhangming

daodejing/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.core.urlresolvers import reverse
import random

from daodejing.models import *

def index(request):
    daodej_list=Daodej.objects.order_by('zhangjie')
    context={'daodej_list':daodej_list}
    return render(request,'daodejing/index.html',context)

def detail(request,daodej_id):
    daodej=get_object_or_404(Daodej,pk=daodej_id)
    return render(request,'daodejing/detail.html',{'daodej':daodej})

def results(request,poll_id):
    poll=get_object_or_404(Poll,pk=poll_id)
    return render(request,'polls/results.html',{'poll':poll})

def vote(request,poll_id):
    p=get_object_or_404(Poll,pk=poll_id)
    try:
        selected_choice=p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request,'polls/detail.html',{
            'poll':p,
            'error_message':"You didn't select a choice.",
            })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(p.id,)))

def getone(request,dbanben=0):
    nmax=Daodej.objects.filter(banben=dbanben).count()
    daodej=get_object_or_404(Daodej,pk=random.randint(1,nmax))
    return render(request,'daodejing/detail.html',{'daodej':daodej})

daodejing/templates/daodejing/detail.html
<h1>{{daodej.zhangming}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}


{{daodej.zhangjie}}<br/>
{{daodej.jingwen}}<br/>

[熟练度说明:]
0：未有接触
1：读过
2：熟读
3：经提示可背出全篇
4：基本能背出全篇
5：熟背
6：熟背，且对意义有整体的了解
7：在6基础上，对每个词语均能解说
8：在7基础上，能融会贯通，用于实践
9：运用之妙存乎一心

daodejing/templates/daodejing/index.html
<h1 align='center'>道德经</h1>
{% if daodej_list %}
	<ul>
	{% for daodej in daodej_list %}
		<li><a href="{% url 'daodejing:detail' daodej.id %}">{{daodej.zhangming}}</a></li><br/>
		{{daodej.zhangjie}} {{daodej.jingwen}}<br/><br/>

	{%endfor %}
	</ul>
{% else %}
	<p>没有可用的章节。</p>
{% endif %}

daodejing/templates/daodejing/results.html
<h1>{{poll.question}}</h1>

<ul>
{% for choice in poll.choice_set.all %}
	<li>{{choice.choice_text}}--{{choice.votes}} vote{{choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{%url 'polls:detail' poll.id %}">Vote again?</a>